"""Workspace inbox for inbound chat attachments.

Channel adapters save files a user sends (photos, documents) into a folder
inside the *task workspace* so the executor agent can read them with its normal
file tools. Because that workspace can be any git repository, the inbox root
writes its own ``.gitignore`` (``*``) so attachments never get committed,
regardless of which repo they land in.

Attachments are transient — only needed while a task runs. To avoid unbounded
disk growth, :func:`make_inbox_dir` opportunistically sweeps sub-directories
older than a TTL each time a new one is created (no background thread needed).
"""

from __future__ import annotations

import hashlib
import shutil
import time
from pathlib import Path
from uuid import uuid4

from fluxion.utils.logger import get_logger

logger = get_logger(__name__)

INBOX_DIRNAME = ".fluxion_inbox"

_GITIGNORE_BODY = "# Auto-generated by Fluxion. Inbound chat attachments — do not commit.\n*\n"


def make_inbox_dir(workspace: Path, *, ttl_hours: float = 0.0, storage_key: str = "") -> Path:
    """Create a scoped sub-dir under ``<workspace>/.fluxion_inbox``.

    A non-empty storage key produces a stable, privacy-preserving directory for
    content-addressed reuse; otherwise a fresh per-message directory is used.
    When ``ttl_hours`` is positive, older directories are deleted first.
    """
    root = workspace / INBOX_DIRNAME
    root.mkdir(parents=True, exist_ok=True)
    gitignore = root / ".gitignore"
    if not gitignore.exists():
        try:
            gitignore.write_text(_GITIGNORE_BODY, encoding="utf-8")
        except OSError:
            pass
    if ttl_hours and ttl_hours > 0:
        sweep_inbox(root, ttl_hours=ttl_hours)
    # A stable key lets a conversation reuse content-addressed attachments
    # without exposing the caller's thread/session identifier in the workspace.
    sub_name = (
        hashlib.sha256(storage_key.encode("utf-8")).hexdigest()[:16]
        if storage_key
        else uuid4().hex[:8]
    )
    sub = root / sub_name
    sub.mkdir(parents=True, exist_ok=True)
    # Refresh the directory age whenever the owning conversation uses it.
    try:
        sub.touch(exist_ok=True)
    except OSError:
        pass
    return sub


def sweep_inbox(root: Path, *, ttl_hours: float) -> int:
    """Delete attachment sub-directories under ``root`` older than ``ttl_hours``.

    Only directories are removed; the inbox ``.gitignore`` is preserved. Returns
    the number of sub-directories deleted. Errors are logged and skipped.
    """
    cutoff = time.time() - ttl_hours * 3600
    removed = 0
    try:
        entries = list(root.iterdir())
    except OSError:
        return 0
    for entry in entries:
        try:
            if not entry.is_dir():
                continue
            if entry.stat().st_mtime >= cutoff:
                continue
            shutil.rmtree(entry, ignore_errors=True)
            removed += 1
        except OSError:
            logger.debug("Failed to sweep inbox entry %s", entry, exc_info=True)
    if removed:
        logger.info("Swept %d expired attachment dir(s) under %s", removed, root)
    return removed
