__all__ = ["__version__"]

# Version resolution priority:
# 1. _version.py generated by setuptools-scm during `pip install` (non-editable)
# 2. setuptools-scm at runtime (editable / dev install in a git checkout)
# 3. importlib.metadata (installed package metadata)
# 4. Fallback placeholder

try:
    from fluxion._version import version as __version__  # type: ignore[import-not-found]
except ImportError:
    try:
        from setuptools_scm import get_version as _scm_version  # type: ignore[import-not-found]

        __version__: str = _scm_version(  # type: ignore[no-redef]
            root="../..", relative_to=__file__
        )
    except Exception:
        try:
            from importlib.metadata import version as _pkg_version

            __version__ = _pkg_version("fluxion")  # type: ignore[no-redef]
        except Exception:
            __version__ = "0.0.0.dev0"  # type: ignore[no-redef]
