from __future__ import annotations

import argparse
import os
import shlex
import sys
from pathlib import Path

from fluxion.availability import COMMANDS, PROVIDERS, detect_executor, detected_default_executor
from fluxion.cli.sub import main as subagent_main
from fluxion.config.settings import Settings


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    if args.command == "init":
        return _init(args)
    if args.command == "doctor":
        return _doctor(args)
    if args.command == "run":
        return _run(args)
    return 2


def _init(args: argparse.Namespace) -> int:
    env_path = Path(args.env_file).expanduser().resolve()
    fluxion_root = env_path.parent
    workspace = Path(args.workspace).expanduser().resolve()

    if not workspace.is_dir():
        return _error(f"Workspace does not exist or is not a directory: {workspace}")
    if env_path.exists() and not args.force:
        return _error(f"{env_path} already exists. Use --force to replace it.")

    executor_snapshot = {
        "executors": {
            provider: {"status": detect_executor(provider).status} for provider in PROVIDERS
        }
    }
    executor = args.executor
    if executor == "auto":
        executor = detected_default_executor(executor_snapshot)

    lines = [
        "# Generated by `fluxion init`.",
        f"FLUXION_ENV_FILE={env_path}",
        f"FLUXION_WORKSPACE_ROOT={fluxion_root}",
        f"FLUXION_DATA_DIR={fluxion_root / 'data'}",
        f"FLUXION_DEFAULT_EXECUTOR={executor}",
        f"FLUXION_ALLOWED_WORKSPACES={workspace}",
        "FLUXION_SLACK_ENABLED=false",
        "FLUXION_SCHEDULER_ENABLED=true",
        "FLUXION_MENU_AUTOSTART_SCHEDULER=true",
        "",
    ]
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text("\n".join(lines), encoding="utf-8")

    available = executor_snapshot["executors"][executor]["status"] == "available"
    print(f"Created {env_path}")
    print(f"Default executor: {executor}")
    print(f"First workspace: {workspace}")
    if not available:
        print(f"[warn] `{COMMANDS[executor]}` was not found on PATH.")
    print()
    print("Next:")
    env_assignment = f"FLUXION_ENV_FILE={shlex.quote(str(env_path))}"
    workspace_arg = shlex.quote(str(workspace))
    print(f"  {env_assignment} fluxion doctor --workspace {workspace_arg}")
    print(f'  {env_assignment} fluxion run --workspace {workspace_arg} "Summarize this project"')
    return 0


def _doctor(args: argparse.Namespace) -> int:
    if args.env_file:
        os.environ["FLUXION_ENV_FILE"] = str(Path(args.env_file).expanduser().resolve())

    settings = Settings.load()
    checks: list[tuple[str, bool, str]] = []
    env_path = _active_env_path()
    checks.append(("config", env_path is not None, str(env_path or "No .env file found")))
    checks.append(
        (
            "data directory",
            _can_create_directory(settings.data_dir),
            str(settings.data_dir),
        )
    )

    executor_results = {
        provider: detect_executor(
            provider,
            configured_command=_configured_command(settings, provider),
        )
        for provider in PROVIDERS
    }
    default_result = executor_results.get(settings.default_executor)
    checks.append(
        (
            "default executor",
            default_result is not None and default_result.status == "available",
            settings.default_executor,
        )
    )

    workspace = Path(args.workspace).expanduser().resolve()
    authorization = settings.authorize_run_workspace(
        raw_workspace=str(workspace),
        mode="read-only",
    )
    checks.append(("current workspace", authorization.allowed, authorization.reason))

    # __file__ is fluxion/cli/main.py, so the package root is two levels up.
    package_root = Path(__file__).resolve().parent.parent
    static_index = package_root / "web" / "static" / "index.html"
    failures = 0
    for name, ok, detail in checks:
        print(f"[{'ok' if ok else 'fail'}] {name}: {detail}")
        failures += not ok

    for provider, result in executor_results.items():
        if provider == settings.default_executor:
            continue
        print(f"[optional] {provider} CLI: {result.detail}")
    print(
        f"[optional] web bundle: {'available' if static_index.exists() else 'not built'} "
        f"({static_index})"
    )

    if default_result is not None and default_result.status == "available":
        print(
            "[note] CLI authentication is verified by the first task. "
            f"If it fails, run `{COMMANDS[settings.default_executor]}` and sign in."
        )
    return 1 if failures else 0


def _run(args: argparse.Namespace) -> int:
    workspace = args.workspace
    if not args.project or workspace != ".":
        workspace = str(Path(workspace).expanduser().resolve())
    forwarded = [
        "--agent",
        args.agent,
        "--workspace",
        workspace,
        "--profile",
        "implement" if args.write else "inspect",
        "--mode",
        "workspace-write" if args.write else "read-only",
    ]
    if args.project:
        forwarded.extend(["--project", args.project])
    if args.json:
        forwarded.append("--json")
    forwarded.extend(args.prompt)
    return subagent_main(forwarded)


def _active_env_path() -> Path | None:
    explicit = os.environ.get("FLUXION_ENV_FILE", "").strip()
    if explicit:
        path = Path(explicit).expanduser().resolve()
        return path if path.is_file() else None
    path = Path(".env").resolve()
    return path if path.is_file() else None


def _configured_command(settings: Settings, provider: str) -> str:
    if provider == "claude":
        return settings.claude_command
    if provider == "antigravity":
        return settings.antigravity_command
    return ""


def _can_create_directory(path: Path) -> bool:
    try:
        path.mkdir(parents=True, exist_ok=True)
        return path.is_dir() and os.access(path, os.W_OK)
    except OSError:
        return False


def _error(message: str) -> int:
    print(f"fluxion: error: {message}", file=sys.stderr)
    return 2


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="fluxion",
        description="Set up, check, and run Fluxion.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="Create a minimal working .env file.")
    init_parser.add_argument("--env-file", default=".env", help="Config file to create.")
    init_parser.add_argument(
        "--workspace",
        default=".",
        help="First workspace Fluxion may access (default: current directory).",
    )
    init_parser.add_argument(
        "--executor",
        choices=["auto", *PROVIDERS],
        default="auto",
        help="Default executor. auto selects the first available CLI.",
    )
    init_parser.add_argument("--force", action="store_true", help="Replace an existing config.")

    doctor_parser = subparsers.add_parser("doctor", help="Check the local Fluxion setup.")
    doctor_parser.add_argument("--env-file", default="", help="Config file to check.")
    doctor_parser.add_argument(
        "--workspace",
        default=".",
        help="Workspace whose read-only authorization should be checked.",
    )

    run_parser = subparsers.add_parser("run", help="Run a task in the current project.")
    run_parser.add_argument("prompt", nargs="+", help="Task prompt.")
    run_parser.add_argument("--agent", default="auto", choices=["auto", *PROVIDERS])
    run_parser.add_argument("--project", default="", help="Configured project key.")
    run_parser.add_argument("--workspace", default=".", help="Target workspace.")
    run_parser.add_argument("--write", action="store_true", help="Allow workspace edits.")
    run_parser.add_argument("--json", action="store_true", help="Print JSON output.")
    return parser.parse_args(argv)


if __name__ == "__main__":
    raise SystemExit(main())
